name: login_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^0.3.0
  font_awesome_flutter: ^8.0.1
  http: ^0.12.0
  dio: ^3.0.0
  equatable: ^0.4.0
  dartz: ^0.8.6
  shared_preferences: ^0.5.3+4
  json_annotation: ^2.0.0
  tuple: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lang/pt.json
    - lang/en.json
