name: login_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.4.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^0.3.0
  font_awesome_flutter: ^8.0.1
  http: ^0.12.0
  dio: ^3.0.5
  equatable: ^0.4.0
  dartz: ^0.8.6
  shared_preferences: ^0.5.3
  json_annotation: ^2.0.0
  device_info: ^0.4.1
  toast: ^0.1.5
  email_validator: ^1.0.0
  moor_flutter: ^1.4.0
  # For the UI
  provider: ^3.0.0+1
  flutter_slidable: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
  moor_generator: ^1.4.0
  build_runner:

flutter:

  uses-material-design: true

  assets:
    - lang/pt_BR.json
    - lang/en_US.json
    - assets/img/
