name: login_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^0.1.2
  scoped_model: ^0.3.0
  font_awesome_flutter: ^8.0.1
  http: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0

flutter:

  uses-material-design: true

  assets:
    - lang/pt.json
    - lang/en.json
